# Generated by Django 4.2.3 on 2023-10-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_searchquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='query',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.product'),
        ),
    ]
