# Generated by Django 4.2.3 on 2023-10-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_remove_searchquery_query_searchquery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.product'),
        ),
    ]
